### PR TITLE
fix `iai_callgrind` metrics

### LINKED ISSUE #453: `rust-iai-callgrind` fails to collect all metrics
`iai-callgrind` has many tools. By default, it only runs `CALLGRIND`, which reports the following six metrics:

```log
iai::benchmarks::test1
  Instructions:          3102359729|3102359161      (+0.00002%) [+1.00000x]
  L1 Hits:               4435753829|4435875893      (-0.00275%) [-1.00003x]
  L2 Hits:                  1199262|1076439         (+11.4101%) [+1.11410x]
  RAM Hits:                   25535|25449           (+0.33793%) [+1.00338x]
  Total read+write:      4436978626|4436977781      (+0.00002%) [+1.00000x]
  Estimated Cycles:      4442643864|4442148803      (+0.01114%) [+1.00011x]
```

But when the `DHAT` tool is additionally enabled, the following metrics are reported as well (and the output is split into two sections):

```log
iai::benchmarks::test1
  ======= CALLGRIND =======================================================
  Instructions:          3102359729|3102359729      (No change)
  L1 Hits:               4435921602|4435921602      (No change)
  L2 Hits:                  1031503|1031503         (No change)
  RAM Hits:                   25521|25521           (No change)
  Total read+write:      4436978626|4436978626      (No change)
  Estimated Cycles:      4441972352|4441972352      (No change)
  ======= DHAT ============================================================
  Total bytes:             26294939|26294939        (No change)
  Total blocks:             2328086|2328086         (No change)
  At t-gmax bytes:           933718|933718          (No change)
  At t-gmax blocks:           18344|18344           (No change)
  At t-end bytes:                 0|0               (No change)
  At t-end blocks:                0|0               (No change)
  Reads bytes:             47577425|47577425        (No change)
  Writes bytes:            37733810|37733810        (No change)
```

Currently they are completely ignored by `bencher run`. I think they need to be added to the list [here](https://github.com/bencherdev/bencher/blob/8be4539d865070820aa8dbc6d6ee763db2f6c02c/lib/bencher_adapter/src/adapters/rust/iai_callgrind.rs#L67-L98).

Additionally, the benchmark name is incorrectly picked up as ` ======= CALLGRIND =======================================================`, instead of `iai::benchmarks::test1`, which should be handled when fixing this.

Here is a Rust repro that enables this additional tool:

```rust
#[library_benchmark]
fn test1() {
    black_box(execute_something());
}

library_benchmark_group!(
    name = benchmarks;
    benchmarks = test1
);

main!(
    config = LibraryBenchmarkConfig::default().tool(Tool::new(ValgrindTool::DHAT));
    library_benchmark_groups = benchmarks
);
```

cc @epompeii

### PR DESCRIPTION
**Pull request by OmarTawfik**
- Fixed an existing bug where existing `CALLGRIND` tool metrics were using an incorrect name/slug from `iai`.
- add metrics from `DHAT` tool
- Fixed the `iai_callgrind` parser to account for either one or multiple tools running, and added some tests for the new format.

Note: I consolidated all the measures into a `mod` hierarchy, to avoid name collisions.
The new consolidated hierarchy can eliminate a lot of the boilerplate code by reusing the generic trait directly. For example, the validators in `lib/bencher_adapter/src/adapters/mod.rs`, or the wrappers `IaiMeasure` and `IaiCallgrindMeasure` in `lib/bencher_adapter/src/results/adapter_results.rs`. But I didn't want to change too much at once, so I left it as is for now. Just pointing this out for future reference.

Closes #453

cc @epompeii

### CODE REVIEW

**Comment by OmarTawfik** [comment]
I think many of these CI jobs are failing as they were trying to use `${{ secrets }}`, which are not available for PR workflows (and they shouldn't be).

File: lib/bencher_json/src/project/measure/defs.rs [hunk 1]
```diff
@@ -0,0 +1,128 @@
+use crate::JsonNewMeasure;
```
Comment (epompeii) [inline lib/bencher_json/src/project/measure/defs.rs:1]: I would prefer a more descriptive name for these definitions than `defs`. What are these definitions for?

My current preference would be for `built_in`. These are Measure definitions that are built-in to Bencher.
I'm open to suggestions though!

File: lib/bencher_json/src/project/measure/defs.rs [hunk 2]
```diff
@@ -0,0 +1,128 @@
...
+use bencher_valid::NameId;
+
+pub trait MeasureDefinition {
```
Comment (epompeii) [inline lib/bencher_json/src/project/measure/defs.rs:4]: Likewise, this should be renamed to `BuiltInMeasure` or whatever we decide.

File: lib/bencher_json/src/project/measure/defs.rs [hunk 3]
```diff
@@ -0,0 +1,128 @@
...
+    const SLUG_STR: &'static str;
+    const UNITS_STR: &'static str;
+
+    fn name_id() -> NameId {
+        Self::SLUG_STR
+            .parse()
+            .expect("Failed to parse measure slug.")
+    }
+
+    fn json_new() -> JsonNewMeasure {
```
Comment (epompeii) [inline lib/bencher_json/src/project/measure/defs.rs:15]: Pedantic, but I would prefer the verb first, so `new_json` instead of `json_new`.

File: services/api/src/model/project/measure.rs [hunk 4]
```diff
@@ -62,6 +58,10 @@ impl QueryMeasure {
         project_id: ProjectId,
         measure: &MeasureNameId,
     ) -> Result<MeasureId, HttpError> {
+        fn test<T: MeasureDefinition>(measure_str: &str) -> Option<JsonNewMeasure> {
```
Comment (epompeii) [inline services/api/src/model/project/measure.rs:61]: Maybe make this an auto-implemented associated function for the trait?

Suggested rename `from_name_id`.

**Review by epompeii — COMMENTED** [review]
Great work! I have just a few comments, mainly small refactors and renames.

> I think many of these CI jobs are failing as they were trying to use ${{ secrets }}, which are not available for PR workflows (and they shouldn't be).

Yes, you are correct. I should probably create an entirely separate PR workflow so this is clearer to contributors. I've gone ahead and created a tracking issue for this: https://github.com/bencherdev/bencher/issues/463
For now, the main concern is that the `Cargo Test PR` job passes. Which it does: https://github.com/bencherdev/bencher/actions/runs/10067844470/job/27832100063

File: lib/bencher_adapter/src/adapters/rust/iai_callgrind.rs [hunk 5]
```diff
@@ -22,313 +26,337 @@ use crate::{
...
+            "./tool_output/rust/iai_callgrind/delta.txt",
+        );
+        validate_adapter_rust_iai_callgrind(&results, true, false);
     }
 
     #[test]
-    fn test_adapter_rust_iai_callgrind() {
-        let results = convert_rust_iai_callgrind("two");
-        validate_adapter_rust_iai_callgrind(&results);
+    fn test_iai_adapter_ansi_escapes() {
```
[the remark this answers is not in the document]
Comment (OmarTawfik) [reply lib/bencher_adapter/src/adapters/rust/iai_callgrind.rs:264]: > Please keep _issue_345 as the test name suffix

Done ..

[the remark this answers is not in the document]
Comment (OmarTawfik) [reply lib/bencher_adapter/src/adapters/rust/iai_callgrind.rs:264]: > are you sure that breaking out the test input to a file creates the proper ANSI characters?

You can view the ANSI characters in the editor locally:

image

Please let me know if there is anything else that can be done.

File: lib/bencher_json/src/project/measure/defs.rs (hunk 2 above)
Comment (OmarTawfik) [reply lib/bencher_json/src/project/measure/defs.rs:4]: Sure

File: lib/bencher_json/src/project/measure/defs.rs (hunk 1 above)
Comment (OmarTawfik) [reply lib/bencher_json/src/project/measure/defs.rs:1]: The `defs` are of the parent module, `measure::defs` -> `Measure Definitions` ..
But happy to change to `built_in`. Will do!

File: lib/bencher_json/src/project/measure/defs.rs (hunk 3 above)
Comment (OmarTawfik) [reply lib/bencher_json/src/project/measure/defs.rs:15]: Sure. I was following the naming of the existing `JsonNewMeasure` type.

File: services/api/src/model/project/measure.rs (hunk 4 above)
Comment (OmarTawfik) [reply services/api/src/model/project/measure.rs:61]: Done.

**Comment by OmarTawfik** [comment]
@epompeii feedback addressed. Thanks!

**Comment by epompeii** [comment]
> Can you please tell me if the backend (production) is deployed when `main` is updated? or is there a separate deployment cadence?

[PRs should target the `devel` branch](https://github.com/bencherdev/bencher?tab=readme-ov-file#-all-pull-requests-should-target-the-devel-branch).

All WIP happens on `devel`. Once `devel` is merged into `cloud`, changes are released to https://bencher.dev and then `main` is rebased on `cloud` by GitHub Actions: https://github.com/bencherdev/bencher/blob/8be4539d865070820aa8dbc6d6ee763db2f6c02c/.github/workflows/bencher.yml#L894
In order for artifacts (CLI and self-hosted Docker images) to be updated, then [a new release](https://github.com/bencherdev/bencher/releases) has to be cut. This is done from the `devel` branch. Then merged into `cloud` which will rebase `main`.
I've added a todo here https://github.com/bencherdev/bencher/issues/320 to document this properly with all of the reasoning.

**Comment by epompeii** [comment]
Looks great! Thank you, @OmarTawfik.
I went ahead and handled the merge conflict myself, since there were some important changes needed for https://github.com/bencherdev/bencher/issues/334.

**Review by epompeii — APPROVED** [review]

**Comment by OmarTawfik** [comment]
@epompeii thanks for the explanation!
What is the cadence to merge to `cloud`/release to <bencher.dev>? I see it was last updated 3 weeks ago.
We are excited to try the new feature once it is deployed. Is there anything I can help with to unblock this?

**Comment by epompeii** [comment]
Usually the cadence is same-day to at the latest once a week. However, my daughter was born two weeks ago 🐣 hence the delay.

With that said, your changes should now be live: https://github.com/bencherdev/bencher/actions/runs/10133440388

**Comment by OmarTawfik** [comment]
Congratulations again! 😄
And no worries at all. Thanks for all of your efforts in building/maintaining this tool!
